from enum import IntEnum

# General
FSM_LOOP_TIME = 20

# Communication
HEADER_0 = 0xAA
HEADER_1 = 0xBB
HEADER_SIZE = 5
TAIL_SIZE = 1

# Sequence Handling
SEQUENCE_BUFFER_LENGTH = 150
RELOAD_NUMBER = 100

# HOST_ADDRESS = '192.168.8.60'
# HOST_ADDRESS = '192.168.0.238'
HOST_ADDRESS = '192.168.0.30'
HOST_PORT = 6666

# PARAMS
IMU_X_POS = 0
IMU_Y_POS = -0.07236
IMU_Z_POS = 0.1106

GRAVITY = 9.81

RADIUS_RIGHT_WHEEL = 108 / 1000 / 2
RADIUS_LEFT_WHEEL = 108 / 1000 / 2
WHEELBASE = 0.200

# MESSAGES
ID_MSG_LL_OUT_DYNAMIC_STATE = 0x01
ID_MSG_LL_OUT_IMU = 0x02
ID_MSG_LL_OUT_DRV = 0x03
ID_MSG_LL_OUT_CTRL_STATE = 0x04
ID_MSG_LL_OUT_FSM = 0x05
ID_MSG_LL_OUT_CTRL_SF_CONFIG = 0x06
ID_MSG_LL_OUT_CTRL_SC_X_CONFIG = 0x07
ID_MSG_LL_OUT_CTRL_SC_PSI_CONFIG = 0x08
ID_MSG_LL_OUT_SENSOR_CONFIG = 0x09
ID_MSG_LL_OUT_ESTIMATION_CONFIG = 0x0A
ID_MSG_LL_OUT_WARNING = 0x0B
ID_MSG_LL_OUT_ERROR = 0x0C
ID_MSG_LL_OUT_ECHO = 0x0E
ID_MSG_LL_OUT_CTRL_INPUT = 0x0F
ID_MSG_LL_OUT_DEBUG = 0xAA
ID_MSG_LL_OUT_HANDSHAKE = 0xAB
ID_MSG_LL_OUT_SV_CTRL = 0xAC
ID_MSG_LL_OUT_RESET_STATE_VEC = 0xAD
ID_MSG_LL_OUT_START_SEQUENCE = 0xAE
ID_MSG_LL_OUT_RELOAD = 0xAF
ID_MSG_LL_OUT_END_SEQUENCE = 0xB0

ID_MSG_LL_IN_FSM = 0x10
ID_MSG_LL_IN_CTRL_INPUT = 0x11
ID_MSG_LL_IN_CTRL_STATE = 0x12
ID_MSG_LL_IN_SF_CONFIG = 0x13
ID_MSG_LL_IN_CTRL_SC_X_CONFIG = 0x14
ID_MSG_LL_IN_CTRL_SC_PSI_CONFIG = 0x15
ID_MSG_LL_IN_EST_ORI_V_CONFIG = 0x16
ID_MSG_LL_IN_EST_ORI_W_CONFIG = 0x17
ID_MSG_LL_IN_ECHO = 0x18
ID_MSG_LL_IN_HEADING = 0x19
ID_MSG_LL_IN_CTRL_INPUT_BUFFER_VEL = 0x1A
ID_MSG_LL_IN_HANDSHAKE = 0x1B
ID_MSG_LL_IN_SV_CTRL = 0x1C
ID_MSG_LL_IN_RESET_STATE_VEC = 0x1D
ID_MSG_LL_IN_START_SEQUENCE = 0x1E
ID_MSG_LL_IN_RELOAD = 0x1F
ID_MSG_LL_IN_END_SEQUENCE = 0x20

ID_MSG_LL_IN_DEBUG = 0xBB

ID_MSG_LL_OUT_INPUT_BUFFER_VEL = 0x1B

ID_MSG_LL_OUT_CONTINIUOUS = 0x1C

ID_MSG_HOST_OUT_DEBUG = 0x40
ID_MSG_HOST_OUT_MOCAP = 0x41
ID_MSG_HOST_OUT_FSM = 0x42
ID_MSG_HOST_OUT_CTRL_STATE = 0x43
ID_MSG_HOST_OUT_CTRL_INPUT = 0x44
ID_MSG_HOST_OUT_CTRL_SF_CONFIG = 0x45
ID_MSG_HOST_OUT_CTRL_SC_X_CONFIG = 0x46
ID_MSG_HOST_OUT_CTRL_SC_PSI_CONFIG = 0x47
ID_MSG_HOST_OUT_SELFTEST = 0x48
ID_MSG_HOST_OUT_CALIBRATION = 0x49
ID_MSG_HOST_OUT_LOGGING = 0x4A
ID_MSG_HOST_OUT_EXPERIMENT = 0x4B
ID_MSG_HOST_OUT_HEADING = 0x4C
ID_MSG_HOST_OUT_MOVE = 0x4D
ID_MSG_HOST_OUT_SV_CTRL = 0x4E
ID_MSG_HOST_OUT_RESET_STATE_VEC = 0x4F
ID_MSG_HOST_OUT_DELAY = 0x50
ID_MSG_HOST_OUT_LOAD_EXPERIMENT = 0x51
ID_MSG_HOST_OUT_LOAD_SEQUENCE = 0x52
ID_MSG_HOST_OUT_START_EXPERIMENT = 0x53
ID_MSG_HOST_OUT_START_SEQUENCE = 0x54
ID_MSG_HOST_OUT_END_EXPERIMENT = 0x55
ID_MSG_HOST_OUT_END_SEQUENCE = 0x56

ID_MSG_HOST_IN_ERROR = 0x60
ID_MSG_HOST_IN_INFO = 0x61
ID_MSG_HOST_IN_DYNAMICS = 0x62
ID_MSG_HOST_IN_FSM = 0x63
ID_MSG_HOST_IN_IMU = 0x64
ID_MSG_HOST_IN_DRIVE = 0x65
ID_MSG_HOST_IN_CTRL_SF_CONFIG = 0x66
ID_MSG_HOST_IN_CTRL_SC_X_CONFIG = 0x67
ID_MSG_HOST_IN_CTRL_SC_PSI_CONFIG = 0x68
ID_MSG_HOST_IN_LOAD_EXPERIMENT = 0x69
ID_MSG_HOST_IN_LOGGING = 0x6A
ID_MSG_HOST_IN_DEBUG = 0x6B
ID_MSG_HOST_IN_CTRL_STATE = 0x6C
ID_MSG_HOST_IN_CONT = 0x6D
ID_MSG_HOST_IN_SV_CTRL = 0x6E
ID_MSG_HOST_IN_CTRL_INPUT = 0x6F
ID_MSG_HOST_IN_RESET_STATE_VEC = 0x70
ID_MSG_HOST_IN_DELAY = 0x71
ID_MSG_HOST_IN_LOAD_SEQUENCE = 0x73
ID_MSG_HOST_IN_START_EXPERIMENT = 0x74
ID_MSG_HOST_IN_START_SEQUENCE = 0x75
ID_MSG_HOST_IN_END_EXPERIMENT = 0x76
ID_MSG_HOST_IN_END_SEQUENCE = 0x77
ID_MSG_HOST_IN_RELOAD = 0x78

ERROR_HL_MSG_HANDLER_BLOCK = 0x08
ERROR_LL_MSG_HANDLER_BLOCK = 0x09
ERROR_CANNOT_SET_CTRL_STATE = 0x10
ERROR_CANNOT_SET_SF_CONFIG = 0x11
ERROR_CANNOT_SET_SC_CONFIG = 0x12
ERROR_MOTOR_LEFT_FAULT = 0x13
ERROR_MOTOR_RIGHT_FAULT = 0x14
ERROR_IMU_FAULT = 0x15
ERROR_CANNOT_SET_ACTIVE_ATTITUDE = 0x16
ERROR_CANNOT_SET_CALIBRATE_ATTITUDE = 0x17
ERROR_SUPERVISOR_MAX_VEL = 0x18
ERROR_SUPERVISOR_MAX_YAW_VEL = 0x19
ERROR_SUPERVISOR_MAX_THETA = 0x20
ERROR_FSM_CANNOT_SWITCH_STATE = 0x21
ERROR_FSM_ALREADY_IN_STATE = 0x22
ERROR_CTRL_CANNOT_SWITCH_STATE = 0x23
ERROR_CTRL_ALREADY_IN_STATE = 0x24
ERROR_CANNOT_SET_CTRL_INPUT = 0x25
ERROR_SUPERVISOR_MAX_TORQUE = 0x26
ERROR_SUPERVISOR_TORQUE_NO_MOVEMENT = 0x27
ERROR_SUPERVISOR_IMU_FAULT = 0x28
ERROR_SUPERVISOR_ENCODER_FAULT = 0x29
ERROR_SUPERVISOR_MAX_THETA_DOT = 0x30
ERROR_SUPERVISOR_IMU_TEST_1 = 0x31
ERROR_SUPERVISOR_IMU_TEST_2 = 0x32
ERROR_SUPERVISOR_IMU_TEST_3 = 0x33
ERROR_CANNOT_SET_SV_CONFIG = 0x34
ERROR_CANNOT_RESET_STATE_VEC = 0x35

ERROR_MSG_CORRUPTED = 0x3F
ERROR_MSG_NOT_IMPLEMENTED = 0x40
ERROR_LL_NOT_CONNECTED = 0x41
ERROR_LL_INIT = 0x42

ERROR_LOGGING_ACTIVATED = 0x70
ERROR_LOGGING_DEACTIVATED = 0x71

ERROR_CANNOT_START_EXPERIMENT = 0x72
ERROR_CANNOT_START_SEQUENCE = 0x73
ERROR_MAX_WAITING_TIME = 0x74
ERROR_RELOADING = 0x75
ERROR_CANNOT_END_EXPERIMENT = 0x76
ERROR_CANNOT_END_SEQUENCE = 0x77
ERROR_DURING_EXPERIMENT = 0x78

ERROR_CANNOT_START_LOGGING = 0x79



